<#
.SYNOPSIS
    Governance Compliance Validator — Sentra Healthcare AI

.DESCRIPTION
    Automated pre-push compliance gate. Checks .gitignore completeness,
    lockfile override sync, .gitattributes normalization, and ESLint coverage.
    Run from the project root before every push.

.PARAMETER check
    Run only a specific check. Options: gitignore, lockfile, gitattributes, eslint, all
    Default: all

.PARAMETER path
    Path to the project root to validate.
    Default: current directory

.EXAMPLE
    # Validate all checks from current directory
    .\validate.ps1

.EXAMPLE
    # Validate from a specific project
    ../../../tooling/governance/validate.ps1 -path V:\sentra-artificial-intelligence\abyss-monorepo\apps\healthcare\sentra-assist

.EXAMPLE
    # Run only lockfile check
    .\validate.ps1 -check lockfile
#>

param(
    [string]$check = "all",
    [string]$path = (Get-Location).Path
)

# ─────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────

$PASS = "[PASS]"
$FAIL = "[FAIL]"
$WARN = "[WARN]"

$totalFails = 0
$totalWarns = 0

function Write-Pass { param([string]$msg) Write-Host "$PASS $msg" -ForegroundColor Green }
function Write-Fail { param([string]$msg) Write-Host "$FAIL $msg" -ForegroundColor Red; $script:totalFails++ }
function Write-Warn { param([string]$msg) Write-Host "$WARN $msg" -ForegroundColor Yellow; $script:totalWarns++ }
function Write-Section { param([string]$title) Write-Host "`n=== $title ===" -ForegroundColor Cyan }

# ─────────────────────────────────────────────
# Check: .gitignore
# ─────────────────────────────────────────────

function Check-Gitignore {
    Write-Section "GITIGNORE COMPLETENESS"

    $gitignorePath = Join-Path $path ".gitignore"

    if (-not (Test-Path $gitignorePath)) {
        Write-Fail ".gitignore not found at $gitignorePath"
        return
    }

    $content = Get-Content $gitignorePath -Raw

    $required = @(
        @{ pattern = "dist/";        label = "dist/" },
        @{ pattern = ".output/";     label = ".output/" },
        @{ pattern = "node_modules/"; label = "node_modules/" },
        @{ pattern = "docs/api/";    label = "docs/api/ (TypeDoc output)" },
        @{ pattern = ".wxt/";        label = ".wxt/ (WXT framework cache)" }
    )

    foreach ($entry in $required) {
        if ($content -match [regex]::Escape($entry.pattern)) {
            Write-Pass "$($entry.label) is ignored"
        } else {
            Write-Fail "$($entry.label) is NOT in .gitignore — auto-generated files may be committed"
        }
    }

    # Optional but recommended
    $optional = @("build/", "docs/storybook/", "coverage/")
    foreach ($entry in $optional) {
        if ($content -notmatch [regex]::Escape($entry)) {
            Write-Warn "$entry not in .gitignore (optional but recommended)"
        }
    }
}

# ─────────────────────────────────────────────
# Check: pnpm-lock.yaml override sync
# ─────────────────────────────────────────────

function Check-Lockfile {
    Write-Section "LOCKFILE OVERRIDE SYNC"

    $lockPath    = Join-Path $path "pnpm-lock.yaml"
    $packagePath = Join-Path $path "package.json"

    if (-not (Test-Path $lockPath)) {
        Write-Fail "pnpm-lock.yaml not found"
        return
    }

    if (-not (Test-Path $packagePath)) {
        Write-Fail "package.json not found"
        return
    }

    # Count overrides in lockfile
    $lockContent  = Get-Content $lockPath -Raw
    $lockOverrides = ([regex]::Matches($lockContent, '(?m)^overrides:')).Count

    if ($lockOverrides -eq 0) {
        Write-Warn "pnpm-lock.yaml has no 'overrides:' section — expected if package.json has pnpm.overrides"
    } else {
        Write-Pass "pnpm-lock.yaml has overrides section"
    }

    # Count overrides in package.json
    $packageJson = Get-Content $packagePath -Raw | ConvertFrom-Json
    $pkgOverrides = 0
    if ($packageJson.pnpm -and $packageJson.pnpm.overrides) {
        $pkgOverrides = ($packageJson.pnpm.overrides | Get-Member -MemberType NoteProperty).Count
    }

    if ($pkgOverrides -eq 0 -and $lockOverrides -eq 0) {
        Write-Pass "No overrides in package.json or lockfile — consistent"
        return
    }

    if ($pkgOverrides -gt 0 -and $lockOverrides -eq 0) {
        Write-Fail "package.json has $pkgOverrides overrides but pnpm-lock.yaml has none — regenerate lockfile"
        Write-Host "    See TROUBLESHOOTING.md Error 1 for fix procedure" -ForegroundColor DarkGray
        return
    }

    Write-Pass "package.json overrides count: $pkgOverrides"

    # Check for "^latest" version strings (sign of incomplete external-agent lockfile)
    if ($lockContent -match '\^latest') {
        Write-Fail "pnpm-lock.yaml contains '^latest' — likely generated by external agent with unpinned versions"
        Write-Host "    See TROUBLESHOOTING.md Error 5 for fix procedure" -ForegroundColor DarkGray
    } else {
        Write-Pass "No '^latest' version strings in lockfile"
    }
}

# ─────────────────────────────────────────────
# Check: .gitattributes
# ─────────────────────────────────────────────

function Check-Gitattributes {
    Write-Section "LINE ENDING NORMALIZATION"

    $attrsPath = Join-Path $path ".gitattributes"

    if (-not (Test-Path $attrsPath)) {
        Write-Fail ".gitattributes not found — Windows CRLF/LF conflicts will cause Prettier pre-push failures"
        Write-Host "    See TROUBLESHOOTING.md Error 4 for fix procedure" -ForegroundColor DarkGray
        Write-Host "    Template: ../../../library/templates/.gitattributes" -ForegroundColor DarkGray
        return
    }

    $content = Get-Content $attrsPath -Raw

    if ($content -match '\* text=auto eol=lf') {
        Write-Pass "* text=auto eol=lf is set"
    } else {
        Write-Fail ".gitattributes missing '* text=auto eol=lf'"
    }

    if ($content -match '\.ps1 text eol=crlf') {
        Write-Pass "*.ps1 CRLF exception is set"
    } else {
        Write-Warn ".gitattributes missing '*.ps1 text eol=crlf' (Windows scripts may break)"
    }
}

# ─────────────────────────────────────────────
# Check: ESLint ignores docs/
# ─────────────────────────────────────────────

function Check-Eslint {
    Write-Section "ESLINT COVERAGE"

    $eslintPath = Join-Path $path "eslint.config.mjs"

    if (-not (Test-Path $eslintPath)) {
        Write-Warn "eslint.config.mjs not found — skipping ESLint coverage check"
        return
    }

    $content = Get-Content $eslintPath -Raw

    if ($content -match "'docs/\*\*'|`"docs/\*\*`"") {
        Write-Pass "docs/** is in ESLint ignores"
    } else {
        Write-Fail "docs/** NOT in ESLint ignores — TypeDoc output will cause lint errors"
        Write-Host "    See TROUBLESHOOTING.md Error 2 for fix procedure" -ForegroundColor DarkGray
    }

    if ($content -match "'.output/\*\*'|`".output/\*\*`"") {
        Write-Pass ".output/** is in ESLint ignores"
    } else {
        Write-Warn ".output/** not in ESLint ignores (recommended for WXT projects)"
    }
}

# ─────────────────────────────────────────────
# Main
# ─────────────────────────────────────────────

Write-Host "`nGovernance Compliance Validator" -ForegroundColor White
Write-Host "Target: $path" -ForegroundColor DarkGray
Write-Host "Check:  $check" -ForegroundColor DarkGray
Write-Host ("─" * 50) -ForegroundColor DarkGray

switch ($check) {
    "gitignore"      { Check-Gitignore }
    "lockfile"       { Check-Lockfile }
    "gitattributes"  { Check-Gitattributes }
    "eslint"         { Check-Eslint }
    "all" {
        Check-Gitignore
        Check-Lockfile
        Check-Gitattributes
        Check-Eslint
    }
    default {
        Write-Host "Unknown check: $check. Options: gitignore, lockfile, gitattributes, eslint, all" -ForegroundColor Red
        exit 1
    }
}

# ─────────────────────────────────────────────
# Summary
# ─────────────────────────────────────────────

Write-Host "`n$("─" * 50)" -ForegroundColor DarkGray

if ($totalFails -eq 0 -and $totalWarns -eq 0) {
    Write-Host "`nALL CHECKS PASSED — safe to push`n" -ForegroundColor Green
    exit 0
} elseif ($totalFails -eq 0) {
    Write-Host "`nPASSED with $totalWarns warning(s) — review warnings before push`n" -ForegroundColor Yellow
    exit 0
} else {
    Write-Host "`nFAILED: $totalFails error(s), $totalWarns warning(s) — fix before push`n" -ForegroundColor Red
    exit 1
}
