// Copyright 2026 Sentra. All rights reserved. Proprietary and confidential.
import fs from 'fs'
import path from 'path'
import type { KnowledgeSourceRegistryEntry, KnowledgeRegistry } from '../registry/registry-types.js'
import type { SkippedRecord } from './types.js'

/**
 * Minimal shape expected in eligible-for-embedding.json.
 * Generated by ABYSS-RAG-003 eligibility-exporter.
 */
interface EligibleEntry {
  source_hash: string
  document_version?: string
  registry_status?: string
}

/**
 * Loads approved candidates from the registry directory.
 *
 * Algorithm:
 * 1. Read eligible-for-embedding.json (candidate list from RAG-003).
 * 2. Read registry.json (authoritative source of truth).
 * 3. Cross-check every candidate against registry.json.
 * 4. Accept ONLY entries with registry_status === 'approved_for_embedding'.
 * 5. All others → skipped with reason.
 *
 * @param registryDir  - Path to data/knowledge-registry
 * @returns approved entries and skipped records
 */
export function loadApprovedCandidates(registryDir: string): {
  approved: KnowledgeSourceRegistryEntry[]
  skipped: SkippedRecord[]
} {
  const eligiblePath = path.join(registryDir, 'eligible-for-embedding.json')
  const registryPath = path.join(registryDir, 'registry.json')

  const approved: KnowledgeSourceRegistryEntry[] = []
  const skipped: SkippedRecord[] = []

  // Load registry (authoritative)
  let registry: KnowledgeRegistry
  if (!fs.existsSync(registryPath)) {
    return { approved, skipped }
  }

  try {
    registry = JSON.parse(fs.readFileSync(registryPath, 'utf-8')) as KnowledgeRegistry
  } catch {
    return { approved, skipped }
  }

  const registryByHash = new Map<string, KnowledgeSourceRegistryEntry>()
  for (const entry of registry.entries ?? []) {
    registryByHash.set(entry.source_hash, entry)
  }

  // Load candidates
  let candidates: EligibleEntry[] = []
  if (fs.existsSync(eligiblePath)) {
    try {
      candidates = JSON.parse(fs.readFileSync(eligiblePath, 'utf-8')) as EligibleEntry[]
    } catch {
      candidates = []
    }
  }

  // If no eligible file, scan registry directly for approved entries
  if (candidates.length === 0) {
    for (const entry of registry.entries ?? []) {
      if (entry.registry_status === 'approved_for_embedding') {
        approved.push(entry)
      }
    }
    return { approved, skipped }
  }

  // Cross-check candidates against registry
  for (const candidate of candidates) {
    const registryEntry = registryByHash.get(candidate.source_hash)

    if (!registryEntry) {
      skipped.push({
        source_hash: candidate.source_hash,
        reason: 'candidate_missing_from_registry',
      })
      continue
    }

    if (registryEntry.registry_status !== 'approved_for_embedding') {
      skipped.push({
        source_hash: candidate.source_hash,
        reason: 'status_not_approved_for_embedding',
        registry_status: registryEntry.registry_status,
      })
      continue
    }

    approved.push(registryEntry)
  }

  return { approved, skipped }
}
