export type TrajectoryCoverageStatus = 'covered' | 'partial' | 'missing'

export interface TrajectoryRegistryEntry {
  id: string
  name: string
  quadrant: 1 | 2 | 3 | 4 | 5
  status: TrajectoryCoverageStatus
  legacyProxy?: string
  missingInputs?: string[]
  adapterNote?: string
}

export const TRAJECTORY_REGISTRY: readonly TrajectoryRegistryEntry[] = [
  // ─── Q5: Legacy Acute Trajectories (T-45 to T-52) — priority quadrant ─────
  { id: 'T-45', name: 'Respiratory Worsening', quadrant: 5, status: 'partial',
    legacyProxy: 'convergence.pattern=respiratory + spo2/rr vitalTrends',
    missingInputs: ['FiO2', 'P/F ratio'],
    adapterNote: 'instabilityPattern: respiratory when convergence.pattern=respiratory' },
  { id: 'T-46', name: 'Hemodynamic Instability', quadrant: 5, status: 'partial',
    legacyProxy: 'convergence.pattern=shock|cardiovascular|hypertensive_crisis',
    missingInputs: ['MAP'],
    adapterNote: 'instabilityPattern: hemodynamic from convergence pattern' },
  { id: 'T-47', name: 'Metabolic Crash', quadrant: 5, status: 'partial',
    legacyProxy: 'convergence.pattern=metabolic_crisis + glucose vitalTrends',
    missingInputs: ['Lactate', 'pH / blood gas'],
    adapterNote: 'instabilityPattern: metabolic from convergence pattern only' },
  { id: 'T-48', name: 'Infectious Surge (CRP Trajectory)', quadrant: 5, status: 'partial',
    legacyProxy: 'LabEvent[].code=CRP slope via classifyInfectiousSurge()',
    missingInputs: ['procalcitonin', 'WBC series', 'validated logistic for CRP-to-sepsis probability'],
    adapterNote: 'classifies active_surge when CRP slope ≥ 37 mg/L/hr (T-48 formula); labsTimeline emitted; instabilityPattern NOT overridden in Phase D — SYMPHONY synthesis only' },
  { id: 'T-49', name: 'Neurologic Decline', quadrant: 5, status: 'partial',
    legacyProxy: 'VisitRecord.vitals.avpu (consciousness proxy)',
    missingInputs: ['GCS series'],
    adapterNote: 'instabilityPattern: neurologic only when AVPU deteriorates; C maps to voice proxy' },
  { id: 'T-50', name: 'Mixed Acute (NEWS2 Aggregate)', quadrant: 5, status: 'partial',
    legacyProxy: 'computeNEWS2() — official NEWS2 scale 1 computed per visit in derivedTimeline',
    missingInputs: ['O2 supplement device flag (always defaults to 0)', 'hypercapnic/COPD flag for Scale 2'],
    adapterNote: 'NEWS2 basis now available; T-50 projection (NEWS2_0 + 1.0×t) requires SYMPHONY' },
  { id: 'T-51', name: 'Treatment Response Good', quadrant: 5, status: 'partial',
    legacyProxy: 'HR slope ≤ −7.9 bpm/hr post-treatment (T-51 formula)',
    missingInputs: ['treatment intervention timeline (TreatmentEvent[] now accepted)', 'post-intervention lab markers', 'validated logistic for response confidence'],
    adapterNote: 'treatmentResponsiveness: responsive when HR slope ≤ −7.9 bpm/hr; unknown if no treatment events or no post-window vital' },
  { id: 'T-52', name: 'Treatment Response Poor', quadrant: 5, status: 'partial',
    legacyProxy: 'HR slope ≥ +2.6 bpm/hr post-treatment (T-52 formula)',
    missingInputs: ['treatment intervention timeline (TreatmentEvent[] now accepted)', 'post-intervention lab markers', 'validated logistic for response confidence'],
    adapterNote: 'treatmentResponsiveness: non_responsive when HR slope ≥ +2.6 bpm/hr; worsening when ≥+2.6 AND SpO2↓≥2pp or RR↑≥4/min; unknown if no treatment events or no post-window vital' },

  // ─── Q2: Perburukan Akut (T-13 to T-24) ───────────────────────────────────
  { id: 'T-13', name: 'Imminent Cardiac Arrest', quadrant: 2, status: 'partial',
    legacyProxy: 'acute_attack_risk_24h.shock_decompensation_risk',
    missingInputs: ['ECG proxy', 'troponin'],
    adapterNote: 'binary risk flag only; no ECG proxy' },
  { id: 'T-14', name: 'Flash ARDS', quadrant: 2, status: 'partial',
    legacyProxy: 'vitalTrends spo2+rr + respiratoryDistressFlag in early_warning_burden',
    missingInputs: ['FiO2', 'PaO2/FiO2 ratio'],
    adapterNote: 'missing FiO2; no P/F ratio' },
  { id: 'T-15', name: 'Neurological Cascade', quadrant: 2, status: 'partial',
    legacyProxy: 'VisitRecord.vitals.avpu',
    missingInputs: ['GCS series', 'focal neurological signs'],
    adapterNote: 'AVPU only; no GCS series' },
  { id: 'T-16', name: 'Sepsis No-Return', quadrant: 2, status: 'partial',
    legacyProxy: 'acute_attack_risk_24h.sepsis_like_deterioration_risk',
    missingInputs: ['lactate', 'WBC', 'procalcitonin'],
    adapterNote: 'flag only; no lab inputs' },
  { id: 'T-17', name: 'T-17 (formula pending)', quadrant: 2, status: 'missing' },
  { id: 'T-18', name: 'T-18 (formula pending)', quadrant: 2, status: 'missing' },
  { id: 'T-19', name: 'T-19 (formula pending)', quadrant: 2, status: 'missing' },
  { id: 'T-20', name: 'T-20 (formula pending)', quadrant: 2, status: 'missing' },
  { id: 'T-21', name: 'T-21 (formula pending)', quadrant: 2, status: 'missing' },
  { id: 'T-22', name: 'T-22 (formula pending)', quadrant: 2, status: 'missing' },
  { id: 'T-23', name: 'T-23 (formula pending)', quadrant: 2, status: 'missing' },
  { id: 'T-24', name: 'T-24 (formula pending)', quadrant: 2, status: 'missing' },

  // ─── Q1: Mortalitas & End-of-Life (T-01 to T-12) ─────────────────────────
  { id: 'T-01', name: 'Imminent Mortality (0–72h)', quadrant: 1, status: 'partial',
    legacyProxy: 'mortality_proxy.mortality_proxy_tier + time_to_critical_estimate',
    missingInputs: ['validated logistic regression inputs', 'lab biomarkers'],
    adapterNote: 'wrong formula; maps to severityBand only; no validated logistic' },
  { id: 'T-02', name: '30-Day Mortality', quadrant: 1, status: 'missing',
    missingInputs: ['30-day horizon (legacy is 5-visit window)'] },
  { id: 'T-03', name: 'Palliative Transition', quadrant: 1, status: 'missing' },
  { id: 'T-04', name: 'Metabolic Age Acceleration', quadrant: 1, status: 'missing' },
  { id: 'T-05', name: 'T-05 (formula pending)', quadrant: 1, status: 'missing' },
  { id: 'T-06', name: 'T-06 (formula pending)', quadrant: 1, status: 'missing' },
  { id: 'T-07', name: 'T-07 (formula pending)', quadrant: 1, status: 'missing' },
  { id: 'T-08', name: 'T-08 (formula pending)', quadrant: 1, status: 'missing' },
  { id: 'T-09', name: 'T-09 (formula pending)', quadrant: 1, status: 'missing' },
  { id: 'T-10', name: 'T-10 (formula pending)', quadrant: 1, status: 'missing' },
  { id: 'T-11', name: 'T-11 (formula pending)', quadrant: 1, status: 'missing' },
  { id: 'T-12', name: 'T-12 (formula pending)', quadrant: 1, status: 'missing' },

  // ─── Q3: Kesehatan Umum & Kronik (T-25 to T-36) ──────────────────────────
  { id: 'T-25', name: 'DM-to-ESRD Baseline', quadrant: 3, status: 'partial',
    legacyProxy: 'VisitRecord.vitals.glucose (PERKENI thresholds only)',
    missingInputs: ['creatinine', 'eGFR'],
    adapterNote: 'no creatinine/eGFR → cannot compute DM-to-ESRD trajectory' },
  { id: 'T-26', name: 'DM-ESRD + Insulin', quadrant: 3, status: 'missing' },
  { id: 'T-27', name: 'DM-ESRD + SGLT2i', quadrant: 3, status: 'missing' },
  { id: 'T-28', name: 'End-Organ Multi-Damage', quadrant: 3, status: 'missing' },
  { id: 'T-29', name: 'Loss of Independence', quadrant: 3, status: 'missing' },
  { id: 'T-30', name: 'Delirium Risk', quadrant: 3, status: 'partial',
    legacyProxy: 'VisitRecord.vitals.avpu',
    missingInputs: ['delirium risk trajectory', 'cognitive assessment series'],
    adapterNote: 'single AVPU point; no delirium risk trajectory model' },
  { id: 'T-31', name: 'T-31 (formula pending)', quadrant: 3, status: 'missing' },
  { id: 'T-32', name: 'T-32 (formula pending)', quadrant: 3, status: 'missing' },
  { id: 'T-33', name: 'T-33 (formula pending)', quadrant: 3, status: 'missing' },
  { id: 'T-34', name: 'T-34 (formula pending)', quadrant: 3, status: 'missing' },
  { id: 'T-35', name: 'T-35 (formula pending)', quadrant: 3, status: 'missing' },
  { id: 'T-36', name: 'T-36 (formula pending)', quadrant: 3, status: 'missing' },

  // ─── Q4: Otoritas Operasional (T-37 to T-44) ─────────────────────────────
  { id: 'T-37', name: 'ICU Escalation Prediction', quadrant: 4, status: 'partial',
    legacyProxy: "mortality_proxy.clinical_urgency_tier === 'immediate'",
    missingInputs: ['dedicated ICU escalation model'],
    adapterNote: 'different granularity; maps to requiresEscalation flag only' },
  { id: 'T-38', name: '30-Day Readmission Prediction', quadrant: 4, status: 'missing' },
  { id: 'T-39', name: 'ICU Bed Congestion', quadrant: 4, status: 'missing' },
  { id: 'T-40', name: 'T-40 (formula pending)', quadrant: 4, status: 'missing' },
  { id: 'T-41', name: 'T-41 (formula pending)', quadrant: 4, status: 'missing' },
  { id: 'T-42', name: 'T-42 (formula pending)', quadrant: 4, status: 'missing' },
  { id: 'T-43', name: 'T-43 (formula pending)', quadrant: 4, status: 'missing' },
  { id: 'T-44', name: 'T-44 (formula pending)', quadrant: 4, status: 'missing' },
] as const
